name: uu-program-verification
version: 21.10
github: "bhaaksema/uu-program-verification"

dependencies:
- base >= 4.7 && < 5
- GCLparser
- z3 >= 408.2
- criterion >= 1.5.10.0

library:
  source-dirs: src

executables:
  uu-program-verification-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uu-program-verification

tests:
  uu-program-verification-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uu-program-verification
