name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: stack build
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: stack test
